version: "3.7"
networks:
    network:
        ipam:
            config:
                - subnet: 172.19.0.0/16
services:
    app:
        build: ./src
        ports:
            - "9001:9001"
        networks:
            network:
                ipv4_address: 172.19.0.3
        volumes:
            - /root/logs/server:/usr/webbackend/src/Logs
        restart: always
        tty: true
    docs:
        build: ./src
        ports:
            - "9001:9001"
        networks:
            network:
                ipv4_address: 172.19.0.4
        volumes:
            - /root/logs/docs:/usr/webbackend/src/Logs
        restart: always
        tty: true
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        restart: always
        tty: true
        networks:
            network:
                ipv4_address: 172.19.0.4
        volumes:
            - /root/logs/nginx:/logs
        depends_on:
            - app
