version: '3.3'
services:
  web:
    build: ./src
    ports:
    - "9001:9001"
    volumes:
    - logvolume:/usr/webbackend/src/logs
  nginx:
    build: ./nginx
    ports:
    - "80:80"
volumes:
  logvolume: {}
