version: '3.7'
services:
  web_app:
    build: ./src
    ports:
    - "9001:9001"
    networks:
    - web
    volumes:
    - /root/logs:/usr/webbackend/src/logs
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    networks:
    - web
    depends_on:
    - web_app
