version: "3.7"
networks:
    web_network:
        ipam:
            config:
                - subnet: 172.19.0.0/16
services:
    web_app:
        build: ./src
        ports:
            - "9001:9001"
        networks:
            web_network:
                ipv4_address: 172.19.0.1
        volumes:
            - /root/logs:/usr/webbackend/src/logs
        restart: always
        tty: true
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        networks:
            web_network:
                ipv4_address: 172.19.0.2
        depends_on:
            - web_app
