
#
FROM python:3.9

#
WORKDIR /src

#
COPY  ./requirements.txt /src/requirements.txt

#
RUN pip install  -r /src/requirements.txt

#
COPY ./ /src/

#
CMD ["uvicorn", "main:app", "--host", "localhost", "--port", "80"]
