"""init

Revision ID: 90c8fcbf3638
Revises: 
Create Date: 2022-01-22 14:28:35.359948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c8fcbf3638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=150), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_auth_group_ID'), 'auth_group', ['ID'], unique=True)
    op.create_index(op.f('ix_auth_group_IdManager'), 'auth_group', ['IdManager'], unique=False)
    op.create_index(op.f('ix_auth_group_TimeUpdate'), 'auth_group', ['TimeUpdate'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_auth_group_permissions_ID'), 'auth_group_permissions', ['ID'], unique=True)
    op.create_index(op.f('ix_auth_group_permissions_IdManager'), 'auth_group_permissions', ['IdManager'], unique=False)
    op.create_index(op.f('ix_auth_group_permissions_TimeUpdate'), 'auth_group_permissions', ['TimeUpdate'], unique=False)
    op.create_table('auth_permission',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_auth_permission_ID'), 'auth_permission', ['ID'], unique=True)
    op.create_index(op.f('ix_auth_permission_IdManager'), 'auth_permission', ['IdManager'], unique=False)
    op.create_index(op.f('ix_auth_permission_TimeUpdate'), 'auth_permission', ['TimeUpdate'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_auth_user_groups_ID'), 'auth_user_groups', ['ID'], unique=True)
    op.create_index(op.f('ix_auth_user_groups_IdManager'), 'auth_user_groups', ['IdManager'], unique=False)
    op.create_index(op.f('ix_auth_user_groups_TimeUpdate'), 'auth_user_groups', ['TimeUpdate'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_auth_user_user_permissions_ID'), 'auth_user_user_permissions', ['ID'], unique=True)
    op.create_index(op.f('ix_auth_user_user_permissions_IdManager'), 'auth_user_user_permissions', ['IdManager'], unique=False)
    op.create_index(op.f('ix_auth_user_user_permissions_TimeUpdate'), 'auth_user_user_permissions', ['TimeUpdate'], unique=False)
    op.create_table('t_cycurricula',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Location', sa.BigInteger(), nullable=True, comment='地点ID'),
    sa.Column('ID_Speaker', sa.BigInteger(), nullable=True, comment='主讲人ID'),
    sa.Column('TimeBegin', sa.Integer(), nullable=True, comment='开始时间'),
    sa.Column('TimeEnd', sa.Integer(), nullable=True, comment='结束时间'),
    sa.Column('Attr', sa.SmallInteger(), nullable=True, comment='类型判断'),
    sa.Column('Charge', sa.SmallInteger(), nullable=True, comment='收费类型字段'),
    sa.Column('PwAccess', sa.SmallInteger(), nullable=True, comment='派位字段'),
    sa.Column('PwContinuous', sa.SmallInteger(), nullable=True, comment='是否连续排位字段'),
    sa.Column('PwDirection', sa.SmallInteger(), nullable=True, comment='排位顺序字段'),
    sa.Column('DoorOpen', sa.SmallInteger(), nullable=True, comment='是否开门字段'),
    sa.Column('TimeBeginCheckBegin', sa.Integer(), nullable=True, comment='考勤开始的时刻表'),
    sa.Column('TimeBeginCheckEnd', sa.Integer(), nullable=True, comment='考勤开始的时刻表'),
    sa.Column('TimeEndCheckBegin', sa.Integer(), nullable=True, comment='考勤结束的时刻表'),
    sa.Column('TimeEndCheckEnd', sa.Integer(), nullable=True, comment='考勤开始的最早时刻表'),
    sa.Column('RangeUsers', sa.Unicode(length=1024), nullable=True, comment='学生学号列表'),
    sa.Column('ListDepts', sa.Unicode(length=1024), nullable=True, comment='部门列表'),
    sa.Column('RangeEqus', sa.Unicode(length=1024), nullable=True, comment='座位范围列表'),
    sa.Column('ListPlaces', sa.Unicode(length=1024), nullable=True, comment='地点列表'),
    sa.Column('MapUser2Equ', sa.Unicode(length=1024), nullable=True, comment='对应列表'),
    sa.Column('AboutSpeaker', sa.Unicode(length=1024), nullable=True, comment='主讲人信息'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cycurricula_Attr'), 't_cycurricula', ['Attr'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_Charge'), 't_cycurricula', ['Charge'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_DoorOpen'), 't_cycurricula', ['DoorOpen'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_ID'), 't_cycurricula', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cycurricula_ID_Location'), 't_cycurricula', ['ID_Location'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_ID_Speaker'), 't_cycurricula', ['ID_Speaker'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_IdManager'), 't_cycurricula', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_PwAccess'), 't_cycurricula', ['PwAccess'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_PwContinuous'), 't_cycurricula', ['PwContinuous'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_PwDirection'), 't_cycurricula', ['PwDirection'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_TimeBegin'), 't_cycurricula', ['TimeBegin'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_TimeEnd'), 't_cycurricula', ['TimeEnd'], unique=False)
    op.create_index(op.f('ix_t_cycurricula_TimeUpdate'), 't_cycurricula', ['TimeUpdate'], unique=False)
    op.create_table('t_cydept',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Parent', sa.BigInteger(), nullable=True, comment='父级部门ID'),
    sa.Column('Name', sa.Unicode(length=32), nullable=True, comment='部门名称'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cydept_ID'), 't_cydept', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cydept_ID_Parent'), 't_cydept', ['ID_Parent'], unique=False)
    op.create_index(op.f('ix_t_cydept_IdManager'), 't_cydept', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cydept_Name'), 't_cydept', ['Name'], unique=False)
    op.create_index(op.f('ix_t_cydept_TimeUpdate'), 't_cydept', ['TimeUpdate'], unique=False)
    op.create_table('t_cyequipment',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Location', sa.BigInteger(), nullable=True, comment='设备所在地ID'),
    sa.Column('ID_User', sa.BigInteger(), nullable=True, comment='设备拥有者ID'),
    sa.Column('Name', sa.Unicode(length=32), nullable=True, comment='设备名称'),
    sa.Column('ID_Location_SN', sa.BigInteger(), nullable=True, comment='位置内编号'),
    sa.Column('ID_IP', sa.Unicode(length=16), nullable=True, comment='IP地址'),
    sa.Column('MAC', sa.Unicode(length=24), nullable=True, comment='MAC地址'),
    sa.Column('State', sa.SmallInteger(), nullable=True, comment='设备状态'),
    sa.Column('Login', sa.SmallInteger(), nullable=True, comment='登陆状态'),
    sa.Column('Link', sa.SmallInteger(), nullable=True, comment='网络状态'),
    sa.Column('Class', sa.SmallInteger(), nullable=True, comment='设备种类'),
    sa.Column('Dx', sa.Integer(), nullable=True, comment='Dx'),
    sa.Column('Dy', sa.Integer(), nullable=True, comment='Dy'),
    sa.Column('iTimeBegin', sa.Integer(), nullable=True),
    sa.Column('iTimeLogin', sa.Integer(), nullable=True),
    sa.Column('WhiteList', sa.Unicode(length=1024), nullable=True, comment='白名单'),
    sa.Column('PortListen', sa.Integer(), nullable=True, comment='接受数据端口'),
    sa.Column('Type', sa.Integer(), nullable=True, comment='刷卡器类型'),
    sa.Column('TimeDelay', sa.Integer(), nullable=True, comment='门禁延迟时间'),
    sa.Column('KeyCancel', sa.Integer(), nullable=True, comment='取消键键码'),
    sa.Column('KeyDel', sa.Integer(), nullable=True, comment='删除键键码'),
    sa.Column('KeyF1', sa.Integer(), nullable=True, comment='功能键键码'),
    sa.Column('OnAll', sa.Integer(), nullable=True, comment='门禁刷卡总是开门'),
    sa.Column('RangeEqus', sa.Unicode(length=64), nullable=True, comment='管理设备范围'),
    sa.Column('ListPlaces', sa.Unicode(length=64), nullable=True, comment='管理地点范围'),
    sa.Column('ID_Plan', sa.BigInteger(), nullable=True, comment='计划ID'),
    sa.Column('KeyOk', sa.Integer(), nullable=True, comment='确定键键码'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cyequipment_Class'), 't_cyequipment', ['Class'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_ID'), 't_cyequipment', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cyequipment_ID_IP'), 't_cyequipment', ['ID_IP'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_ID_Location'), 't_cyequipment', ['ID_Location'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_ID_Location_SN'), 't_cyequipment', ['ID_Location_SN'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_ID_Plan'), 't_cyequipment', ['ID_Plan'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_ID_User'), 't_cyequipment', ['ID_User'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_IdManager'), 't_cyequipment', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_Link'), 't_cyequipment', ['Link'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_Login'), 't_cyequipment', ['Login'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_Name'), 't_cyequipment', ['Name'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_State'), 't_cyequipment', ['State'], unique=False)
    op.create_index(op.f('ix_t_cyequipment_TimeUpdate'), 't_cyequipment', ['TimeUpdate'], unique=False)
    op.create_table('t_cylocation',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Parent', sa.BigInteger(), nullable=True, comment='上级位置ID'),
    sa.Column('Name', sa.Unicode(length=32), nullable=True, comment='位置名称'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cylocation_ID'), 't_cylocation', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cylocation_ID_Parent'), 't_cylocation', ['ID_Parent'], unique=False)
    op.create_index(op.f('ix_t_cylocation_IdManager'), 't_cylocation', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cylocation_Name'), 't_cylocation', ['Name'], unique=False)
    op.create_index(op.f('ix_t_cylocation_TimeUpdate'), 't_cylocation', ['TimeUpdate'], unique=False)
    op.create_table('t_cylocationex',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Location', sa.BigInteger(), nullable=True, comment='位置的唯一标识'),
    sa.Column('Attr', sa.SmallInteger(), nullable=True),
    sa.Column('DateBegin', sa.Integer(), nullable=True),
    sa.Column('DateEnd', sa.Integer(), nullable=True),
    sa.Column('ModeRun', sa.Integer(), nullable=True),
    sa.Column('ModeShangJi', sa.Integer(), nullable=True),
    sa.Column('EnableDelayCharged', sa.Integer(), nullable=True),
    sa.Column('DelayCharged', sa.Integer(), nullable=True),
    sa.Column('EnableLimitYuE_SJ', sa.Integer(), nullable=True),
    sa.Column('LimitYuE_SJ', sa.Integer(), nullable=True),
    sa.Column('EnableLimitYuE_XJ', sa.Integer(), nullable=True),
    sa.Column('LimitYuE_XJ', sa.Integer(), nullable=True),
    sa.Column('EnableLimitTime_XJ', sa.Integer(), nullable=True),
    sa.Column('LimitTime_XJ', sa.Integer(), nullable=True),
    sa.Column('EnableWarnYuE', sa.Integer(), nullable=True),
    sa.Column('WarnYuE', sa.Integer(), nullable=True),
    sa.Column('EnableWarnTime', sa.Integer(), nullable=True),
    sa.Column('WarnTime', sa.Integer(), nullable=True),
    sa.Column('EnableMinCost', sa.Integer(), nullable=True),
    sa.Column('MinCost', sa.Integer(), nullable=True),
    sa.Column('Price', sa.Integer(), nullable=True),
    sa.Column('PriceMinute', sa.Integer(), nullable=True),
    sa.Column('GetEquName', sa.Integer(), nullable=True),
    sa.Column('GetEquIp', sa.Integer(), nullable=True),
    sa.Column('GetEquMac', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cylocationex_Attr'), 't_cylocationex', ['Attr'], unique=False)
    op.create_index(op.f('ix_t_cylocationex_DateBegin'), 't_cylocationex', ['DateBegin'], unique=False)
    op.create_index(op.f('ix_t_cylocationex_DateEnd'), 't_cylocationex', ['DateEnd'], unique=False)
    op.create_index(op.f('ix_t_cylocationex_ID'), 't_cylocationex', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cylocationex_ID_Location'), 't_cylocationex', ['ID_Location'], unique=False)
    op.create_index(op.f('ix_t_cylocationex_IdManager'), 't_cylocationex', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cylocationex_TimeUpdate'), 't_cylocationex', ['TimeUpdate'], unique=False)
    op.create_table('t_cymmx',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Data', sa.BigInteger(), nullable=True, comment='媒体内容的ID'),
    sa.Column('ID_Type', sa.SmallInteger(), nullable=True, comment='媒体类型'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cymmx_ID'), 't_cymmx', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cymmx_ID_Data'), 't_cymmx', ['ID_Data'], unique=False)
    op.create_index(op.f('ix_t_cymmx_ID_Type'), 't_cymmx', ['ID_Type'], unique=False)
    op.create_index(op.f('ix_t_cymmx_IdManager'), 't_cymmx', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cymmx_TimeUpdate'), 't_cymmx', ['TimeUpdate'], unique=False)
    op.create_table('t_cymmxdata',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('Data', sa.Unicode(length=1024), nullable=True, comment='媒体的内容'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cymmxdata_ID'), 't_cymmxdata', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cymmxdata_IdManager'), 't_cymmxdata', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cymmxdata_TimeUpdate'), 't_cymmxdata', ['TimeUpdate'], unique=False)
    op.create_table('t_cyplan',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Curricula', sa.BigInteger(), nullable=True, comment='课程ID'),
    sa.Column('ID_Location', sa.BigInteger(), nullable=True, comment='地点ID'),
    sa.Column('ID_Speaker', sa.BigInteger(), nullable=True, comment='主讲人ID'),
    sa.Column('TimeBegin', sa.Integer(), nullable=True, comment='开始时间'),
    sa.Column('TimeEnd', sa.Integer(), nullable=True, comment='结束时间'),
    sa.Column('Attr', sa.SmallInteger(), nullable=True, comment='类型判断'),
    sa.Column('Charge', sa.SmallInteger(), nullable=True, comment='收费类型字段'),
    sa.Column('PwAccess', sa.SmallInteger(), nullable=True, comment='派位字段'),
    sa.Column('PwContinuous', sa.SmallInteger(), nullable=True, comment='是否连续排位字段'),
    sa.Column('PwDirection', sa.SmallInteger(), nullable=True, comment='排位顺序字段'),
    sa.Column('DoorOpen', sa.SmallInteger(), nullable=True, comment='是否开门字段'),
    sa.Column('TimeBeginCheckBegin', sa.Integer(), nullable=True, comment='考勤开始的时刻表'),
    sa.Column('TimeBeginCheckEnd', sa.Integer(), nullable=True, comment='考勤开始的时刻表'),
    sa.Column('TimeEndCheckBegin', sa.Integer(), nullable=True, comment='考勤结束的时刻表'),
    sa.Column('TimeEndCheckEnd', sa.Integer(), nullable=True, comment='考勤开始的最早时刻表'),
    sa.Column('RangeUsers', sa.Unicode(length=1024), nullable=True, comment='学生学号列表'),
    sa.Column('ListDepts', sa.Unicode(length=1024), nullable=True, comment='部门列表'),
    sa.Column('RangeEqus', sa.Unicode(length=1024), nullable=True, comment='座位范围列表'),
    sa.Column('ListPlaces', sa.Unicode(length=1024), nullable=True, comment='地点列表'),
    sa.Column('MapUser2Equ', sa.Unicode(length=1024), nullable=True, comment='对应列表'),
    sa.Column('AboutSpeaker', sa.Unicode(length=1024), nullable=True, comment='主讲人信息'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cyplan_Attr'), 't_cyplan', ['Attr'], unique=False)
    op.create_index(op.f('ix_t_cyplan_Charge'), 't_cyplan', ['Charge'], unique=False)
    op.create_index(op.f('ix_t_cyplan_DoorOpen'), 't_cyplan', ['DoorOpen'], unique=False)
    op.create_index(op.f('ix_t_cyplan_ID'), 't_cyplan', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cyplan_ID_Curricula'), 't_cyplan', ['ID_Curricula'], unique=False)
    op.create_index(op.f('ix_t_cyplan_ID_Location'), 't_cyplan', ['ID_Location'], unique=False)
    op.create_index(op.f('ix_t_cyplan_ID_Speaker'), 't_cyplan', ['ID_Speaker'], unique=False)
    op.create_index(op.f('ix_t_cyplan_IdManager'), 't_cyplan', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cyplan_PwAccess'), 't_cyplan', ['PwAccess'], unique=False)
    op.create_index(op.f('ix_t_cyplan_PwContinuous'), 't_cyplan', ['PwContinuous'], unique=False)
    op.create_index(op.f('ix_t_cyplan_PwDirection'), 't_cyplan', ['PwDirection'], unique=False)
    op.create_index(op.f('ix_t_cyplan_TimeBegin'), 't_cyplan', ['TimeBegin'], unique=False)
    op.create_index(op.f('ix_t_cyplan_TimeEnd'), 't_cyplan', ['TimeEnd'], unique=False)
    op.create_index(op.f('ix_t_cyplan_TimeUpdate'), 't_cyplan', ['TimeUpdate'], unique=False)
    op.create_table('t_cyrunningaccount',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_User', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('Time', sa.BigInteger(), nullable=True, comment='生成记录的时间'),
    sa.Column('Type', sa.SmallInteger(), nullable=True, comment='记录的类型'),
    sa.Column('Money', sa.Integer(), nullable=True, comment='发生的费用'),
    sa.Column('Param1', sa.BigInteger(), nullable=True, comment='考勤机编号'),
    sa.Column('Param2', sa.BigInteger(), nullable=True, comment='安排编号'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cyrunningaccount_ID'), 't_cyrunningaccount', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cyrunningaccount_ID_User'), 't_cyrunningaccount', ['ID_User'], unique=False)
    op.create_index(op.f('ix_t_cyrunningaccount_IdManager'), 't_cyrunningaccount', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cyrunningaccount_Param1'), 't_cyrunningaccount', ['Param1'], unique=False)
    op.create_index(op.f('ix_t_cyrunningaccount_Param2'), 't_cyrunningaccount', ['Param2'], unique=False)
    op.create_index(op.f('ix_t_cyrunningaccount_Time'), 't_cyrunningaccount', ['Time'], unique=False)
    op.create_index(op.f('ix_t_cyrunningaccount_TimeUpdate'), 't_cyrunningaccount', ['TimeUpdate'], unique=False)
    op.create_index(op.f('ix_t_cyrunningaccount_Type'), 't_cyrunningaccount', ['Type'], unique=False)
    op.create_table('t_cytableinfo',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('Name', sa.Unicode(length=50), nullable=True),
    sa.Column('NameTable', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cytableinfo_ID'), 't_cytableinfo', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cytableinfo_IdManager'), 't_cytableinfo', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cytableinfo_Name'), 't_cytableinfo', ['Name'], unique=False)
    op.create_index(op.f('ix_t_cytableinfo_NameTable'), 't_cytableinfo', ['NameTable'], unique=False)
    op.create_index(op.f('ix_t_cytableinfo_TimeUpdate'), 't_cytableinfo', ['TimeUpdate'], unique=False)
    op.create_table('t_cytypera',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('ID_Parent', sa.BigInteger(), nullable=True, comment='上级类型的ID'),
    sa.Column('Name', sa.Unicode(length=128), nullable=True, comment='类型名称'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cytypera_ID'), 't_cytypera', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cytypera_ID_Parent'), 't_cytypera', ['ID_Parent'], unique=False)
    op.create_index(op.f('ix_t_cytypera_IdManager'), 't_cytypera', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cytypera_Name'), 't_cytypera', ['Name'], unique=False)
    op.create_index(op.f('ix_t_cytypera_TimeUpdate'), 't_cytypera', ['TimeUpdate'], unique=False)
    op.create_table('t_cyuser',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('Deptid', sa.BigInteger(), nullable=True, comment='用户所在部门的ID'),
    sa.Column('NoCard', sa.Unicode(length=32), nullable=True, comment='卡号'),
    sa.Column('NoUser', sa.Unicode(length=32), nullable=True, comment='账号（学工号）'),
    sa.Column('Name', sa.Unicode(length=32), nullable=True, comment='用户名'),
    sa.Column('Psw', sa.Unicode(length=32), nullable=True, comment='密码'),
    sa.Column('Sex', sa.SmallInteger(), nullable=True, comment='用户性别'),
    sa.Column('Attr', sa.SmallInteger(), nullable=True, comment='用户管理权限'),
    sa.Column('AttrJf', sa.SmallInteger(), nullable=True, comment='机房管理权限'),
    sa.Column('Email', sa.Unicode(length=254), nullable=True),
    sa.Column('Phone', sa.Integer(), nullable=True),
    sa.Column('Yue', sa.Integer(), nullable=True, comment='用户余额1'),
    sa.Column('Yue2', sa.Integer(), nullable=True, comment='用户余额2'),
    sa.Column('LocalID', sa.Unicode(length=1024), nullable=True, comment='管理房间的ID列表'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cyuser_Attr'), 't_cyuser', ['Attr'], unique=False)
    op.create_index(op.f('ix_t_cyuser_AttrJf'), 't_cyuser', ['AttrJf'], unique=False)
    op.create_index(op.f('ix_t_cyuser_Deptid'), 't_cyuser', ['Deptid'], unique=False)
    op.create_index(op.f('ix_t_cyuser_Email'), 't_cyuser', ['Email'], unique=False)
    op.create_index(op.f('ix_t_cyuser_ID'), 't_cyuser', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cyuser_IdManager'), 't_cyuser', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cyuser_Name'), 't_cyuser', ['Name'], unique=False)
    op.create_index(op.f('ix_t_cyuser_NoCard'), 't_cyuser', ['NoCard'], unique=False)
    op.create_index(op.f('ix_t_cyuser_NoUser'), 't_cyuser', ['NoUser'], unique=False)
    op.create_index(op.f('ix_t_cyuser_Phone'), 't_cyuser', ['Phone'], unique=False)
    op.create_index(op.f('ix_t_cyuser_Psw'), 't_cyuser', ['Psw'], unique=False)
    op.create_index(op.f('ix_t_cyuser_Sex'), 't_cyuser', ['Sex'], unique=False)
    op.create_index(op.f('ix_t_cyuser_TimeUpdate'), 't_cyuser', ['TimeUpdate'], unique=False)
    op.create_table('t_cyuserex',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Rem', sa.Unicode(length=64), nullable=True),
    sa.Column('Introduction', sa.Unicode(length=254), nullable=True),
    sa.Column('TimeUpdate', sa.BigInteger(), nullable=True),
    sa.Column('IdManager', sa.BigInteger(), nullable=True),
    sa.Column('IMark', sa.Integer(), nullable=True),
    sa.Column('back_up1', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up2', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up3', sa.Unicode(length=254), nullable=True),
    sa.Column('back_up4', sa.Integer(), nullable=True),
    sa.Column('back_up5', sa.Integer(), nullable=True),
    sa.Column('back_up6', sa.Integer(), nullable=True),
    sa.Column('Photo', sa.LargeBinary(), nullable=True, comment='头像'),
    sa.Column('Photo_dataF', sa.Unicode(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_t_cyuserex_ID'), 't_cyuserex', ['ID'], unique=True)
    op.create_index(op.f('ix_t_cyuserex_IdManager'), 't_cyuserex', ['IdManager'], unique=False)
    op.create_index(op.f('ix_t_cyuserex_TimeUpdate'), 't_cyuserex', ['TimeUpdate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_cyuserex_TimeUpdate'), table_name='t_cyuserex')
    op.drop_index(op.f('ix_t_cyuserex_IdManager'), table_name='t_cyuserex')
    op.drop_index(op.f('ix_t_cyuserex_ID'), table_name='t_cyuserex')
    op.drop_table('t_cyuserex')
    op.drop_index(op.f('ix_t_cyuser_TimeUpdate'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Sex'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Psw'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Phone'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_NoUser'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_NoCard'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Name'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_IdManager'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_ID'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Email'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Deptid'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_AttrJf'), table_name='t_cyuser')
    op.drop_index(op.f('ix_t_cyuser_Attr'), table_name='t_cyuser')
    op.drop_table('t_cyuser')
    op.drop_index(op.f('ix_t_cytypera_TimeUpdate'), table_name='t_cytypera')
    op.drop_index(op.f('ix_t_cytypera_Name'), table_name='t_cytypera')
    op.drop_index(op.f('ix_t_cytypera_IdManager'), table_name='t_cytypera')
    op.drop_index(op.f('ix_t_cytypera_ID_Parent'), table_name='t_cytypera')
    op.drop_index(op.f('ix_t_cytypera_ID'), table_name='t_cytypera')
    op.drop_table('t_cytypera')
    op.drop_index(op.f('ix_t_cytableinfo_TimeUpdate'), table_name='t_cytableinfo')
    op.drop_index(op.f('ix_t_cytableinfo_NameTable'), table_name='t_cytableinfo')
    op.drop_index(op.f('ix_t_cytableinfo_Name'), table_name='t_cytableinfo')
    op.drop_index(op.f('ix_t_cytableinfo_IdManager'), table_name='t_cytableinfo')
    op.drop_index(op.f('ix_t_cytableinfo_ID'), table_name='t_cytableinfo')
    op.drop_table('t_cytableinfo')
    op.drop_index(op.f('ix_t_cyrunningaccount_Type'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_TimeUpdate'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_Time'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_Param2'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_Param1'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_IdManager'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_ID_User'), table_name='t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyrunningaccount_ID'), table_name='t_cyrunningaccount')
    op.drop_table('t_cyrunningaccount')
    op.drop_index(op.f('ix_t_cyplan_TimeUpdate'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_TimeEnd'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_TimeBegin'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_PwDirection'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_PwContinuous'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_PwAccess'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_IdManager'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_ID_Speaker'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_ID_Location'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_ID_Curricula'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_ID'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_DoorOpen'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_Charge'), table_name='t_cyplan')
    op.drop_index(op.f('ix_t_cyplan_Attr'), table_name='t_cyplan')
    op.drop_table('t_cyplan')
    op.drop_index(op.f('ix_t_cymmxdata_TimeUpdate'), table_name='t_cymmxdata')
    op.drop_index(op.f('ix_t_cymmxdata_IdManager'), table_name='t_cymmxdata')
    op.drop_index(op.f('ix_t_cymmxdata_ID'), table_name='t_cymmxdata')
    op.drop_table('t_cymmxdata')
    op.drop_index(op.f('ix_t_cymmx_TimeUpdate'), table_name='t_cymmx')
    op.drop_index(op.f('ix_t_cymmx_IdManager'), table_name='t_cymmx')
    op.drop_index(op.f('ix_t_cymmx_ID_Type'), table_name='t_cymmx')
    op.drop_index(op.f('ix_t_cymmx_ID_Data'), table_name='t_cymmx')
    op.drop_index(op.f('ix_t_cymmx_ID'), table_name='t_cymmx')
    op.drop_table('t_cymmx')
    op.drop_index(op.f('ix_t_cylocationex_TimeUpdate'), table_name='t_cylocationex')
    op.drop_index(op.f('ix_t_cylocationex_IdManager'), table_name='t_cylocationex')
    op.drop_index(op.f('ix_t_cylocationex_ID_Location'), table_name='t_cylocationex')
    op.drop_index(op.f('ix_t_cylocationex_ID'), table_name='t_cylocationex')
    op.drop_index(op.f('ix_t_cylocationex_DateEnd'), table_name='t_cylocationex')
    op.drop_index(op.f('ix_t_cylocationex_DateBegin'), table_name='t_cylocationex')
    op.drop_index(op.f('ix_t_cylocationex_Attr'), table_name='t_cylocationex')
    op.drop_table('t_cylocationex')
    op.drop_index(op.f('ix_t_cylocation_TimeUpdate'), table_name='t_cylocation')
    op.drop_index(op.f('ix_t_cylocation_Name'), table_name='t_cylocation')
    op.drop_index(op.f('ix_t_cylocation_IdManager'), table_name='t_cylocation')
    op.drop_index(op.f('ix_t_cylocation_ID_Parent'), table_name='t_cylocation')
    op.drop_index(op.f('ix_t_cylocation_ID'), table_name='t_cylocation')
    op.drop_table('t_cylocation')
    op.drop_index(op.f('ix_t_cyequipment_TimeUpdate'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_State'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_Name'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_Login'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_Link'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_IdManager'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_ID_User'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_ID_Plan'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_ID_Location_SN'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_ID_Location'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_ID_IP'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_ID'), table_name='t_cyequipment')
    op.drop_index(op.f('ix_t_cyequipment_Class'), table_name='t_cyequipment')
    op.drop_table('t_cyequipment')
    op.drop_index(op.f('ix_t_cydept_TimeUpdate'), table_name='t_cydept')
    op.drop_index(op.f('ix_t_cydept_Name'), table_name='t_cydept')
    op.drop_index(op.f('ix_t_cydept_IdManager'), table_name='t_cydept')
    op.drop_index(op.f('ix_t_cydept_ID_Parent'), table_name='t_cydept')
    op.drop_index(op.f('ix_t_cydept_ID'), table_name='t_cydept')
    op.drop_table('t_cydept')
    op.drop_index(op.f('ix_t_cycurricula_TimeUpdate'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_TimeEnd'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_TimeBegin'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_PwDirection'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_PwContinuous'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_PwAccess'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_IdManager'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_ID_Speaker'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_ID_Location'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_ID'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_DoorOpen'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_Charge'), table_name='t_cycurricula')
    op.drop_index(op.f('ix_t_cycurricula_Attr'), table_name='t_cycurricula')
    op.drop_table('t_cycurricula')
    op.drop_index(op.f('ix_auth_user_user_permissions_TimeUpdate'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('ix_auth_user_user_permissions_IdManager'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('ix_auth_user_user_permissions_ID'), table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index(op.f('ix_auth_user_groups_TimeUpdate'), table_name='auth_user_groups')
    op.drop_index(op.f('ix_auth_user_groups_IdManager'), table_name='auth_user_groups')
    op.drop_index(op.f('ix_auth_user_groups_ID'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index(op.f('ix_auth_permission_TimeUpdate'), table_name='auth_permission')
    op.drop_index(op.f('ix_auth_permission_IdManager'), table_name='auth_permission')
    op.drop_index(op.f('ix_auth_permission_ID'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('ix_auth_group_permissions_TimeUpdate'), table_name='auth_group_permissions')
    op.drop_index(op.f('ix_auth_group_permissions_IdManager'), table_name='auth_group_permissions')
    op.drop_index(op.f('ix_auth_group_permissions_ID'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('ix_auth_group_TimeUpdate'), table_name='auth_group')
    op.drop_index(op.f('ix_auth_group_IdManager'), table_name='auth_group')
    op.drop_index(op.f('ix_auth_group_ID'), table_name='auth_group')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
