"""update

Revision ID: 9e02df0b02ea
Revises: 90c8fcbf3638
Create Date: 2022-01-22 14:57:17.658367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e02df0b02ea'
down_revision = '90c8fcbf3638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_cycurricula', sa.Column('Name', sa.Unicode(length=64), nullable=True, comment='课程名称'))
    op.create_index(op.f('ix_t_cycurricula_Name'), 't_cycurricula', ['Name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_cycurricula_Name'), table_name='t_cycurricula')
    op.drop_column('t_cycurricula', 'Name')
    # ### end Alembic commands ###
